services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        value: $TELE_KEY
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: $SPEECH_KEY